[project]
name = "commutehell"
version = "0.1.0"
description = "A simple app that tells you if your commute home will be smooth "
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=2.0.0",
    "python-dotenv>=1.2.2",
    "xmltodict>=1.0.4",
]

[project.scripts]
commutehell = "commutehell.server:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
